# Copyright DXC Technology 2019
#
# Invokes the master template with all required parameters. Serves as a parameter store.
#
# author: Juan Alvarez Ferrando
#

AWSTemplateFormatVersion: 2010-09-09

Description: Stores parameter values and invokes the OHDSI master template

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Templates S3 Location
      Parameters:
        - S3TemplatesBucket
        - S3TemplatesPrefix
    - Label:
        default: Public or Private Deployment
      Parameters:
        - AccessType

    ParameterLabels:
      S3TemplatesBucket:
        default: Bucket Where S3 CFN Templates are stored
      S3TemplatesPrefix:
        default: Prefix of the templates location in the bucket. Use / if none

      AccessType:
        default: Public or Private Access

Parameters:
  S3TemplatesBucket:
    Type: String
    Description: '[ REQUIRED ] Name of the bucket where the CFN templates are stored'
    Default: ohdsi-rstudio
    AllowedPattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
  S3TemplatesPrefix:
    Type: String
    Description: '[ REQUIRED ] Path in the bucket where the CFN templates are stored'
    Default: /

  AccessType:
    Type: String
    Description: Choose between Public or Private access
    AllowedValues:
      - Public
      - Private
    Default: Public

Conditions:
  IsPublic: !Equals
    - !Ref AccessType
    - Public

Resources:
  DBPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Postgres and Redshift databases master password
      Name: OHDSI/DatabaseMasterPassword
      GenerateSecretString: 
        ExcludeCharacters: '!"$&''()./:;<=>?@[\]`{|}'
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 30
        RequireEachIncludedType: true
      KmsKeyId: !ImportValue OHDSI-POC-KmsKeyArn

  AtlasPasswordCdamien:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Atlas WebAPI user Damien Caldy password
      Name: OHDSI/users/cdamien
      GenerateSecretString: 
        ExcludeCharacters: '!"$&''()./:;<=>?@[\]`{|}'
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 10
        RequireEachIncludedType: true
      KmsKeyId: !ImportValue OHDSI-POC-KmsKeyArn

  AtlasPasswordLcobler:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Atlas WebAPI user Lara Cobler password
      Name: OHDSI/users/lcobler
      GenerateSecretString: 
        ExcludeCharacters: '!"$&''()./:;<=>?@[\]`{|}'
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 10
        RequireEachIncludedType: true
      KmsKeyId: !ImportValue OHDSI-POC-KmsKeyArn

  AtlasPasswordFlozano3:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Atlas WebAPI user Fco Lozano password
      Name: OHDSI/users/flozano3
      GenerateSecretString: 
        ExcludeCharacters: '!"$&''()./:;<=>?@[\]`{|}'
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: false
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 10
        RequireEachIncludedType: true
      KmsKeyId: !ImportValue OHDSI-POC-KmsKeyArn

  MasterStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DBPasswordSecret
      - AtlasPasswordCdamien
      - AtlasPasswordLcobler
      - AtlasPasswordFlozano3 
    Properties:
      TemplateURL: !Join 
        - "/"
        - - "https://s3.amazonaws.com"
          - !Ref S3TemplatesBucket
          - !Ref S3TemplatesPrefix 
          - !If
            - IsPublic
            - "00-master-ohdsi.yaml"
            - "00-master-ohdsiprivate.yaml"
      Parameters:
        S3TemplatesBucket: !Ref S3TemplatesBucket
        S3TemplatesPrefix: !Ref S3TemplatesPrefix
        EC2KeyName: !ImportValue OHDSI-POC-InstanceKeyName
        AccessCidr: 0.0.0.0/0
        EBEndpoint: dxc-lsorp
        UseRoute53Boolean: true
        UseACMBoolean: true
        HostedZoneId: !ImportValue LZ-DNS-dxc-lsorp-com-zones-PublicZoneId
        HostedZoneName: dxc-lsorp.com
        DomainName: poc
        MultiAZDatabase: false
        DatabaseInstanceType: db.t3.medium
        RedshiftInstanceType: dc2.large
        DatabaseMasterPassword: '{{resolve:secretsmanager:OHDSI/DatabaseMasterPassword}}'
        NumRedshiftNodes: 1
        Sources: CMSDESynPUF100k,CMSDESynPUF1k,synthea100k,synthea1k
        SourcesBucket: !ImportValue OHDSI-POC-OmopData-BucketName
        WebInstanceType: t3.medium
        WebAsgMax: 2
        WebAsgMin: 1
        WebAsgDesired: 1
        AtlasSecurity: true
        RStudioInstanceType: t3.medium
        RStudioHomeDirectorySize: 50
        RStudioUserList: !Join
          - ","
          - - cdamien
            - '{{resolve::secretsmanager:OHDSI/users/cdamien:password}}'
            - lcobler
            - '{{resolve::secretsmanager:OHDSI/users/lcobler:password}}'
            - flozano3
            - '{{resolve::secretsmanager:OHDSI/users/flozano3:password}}'
        SageMakerBucket: !ImportValue OHDSI-POC-SageMaker-BucketName
        OMOPv: '5.3.1'
        Atlasv: '2.7.2'
        WebAPIv: '2.7.2'
        Achillesv: '1.6.3'
        PatientLevelPredictionv: '3.0.5'
        CohortMethodv: '3.0.2'
        SqlRenderv: '1.6.2'
        DatabaseConnectorv: '2.2.0'
        DatabaseConnectorJarsv: '1.0.0'
        OhdsiRToolsv: '1.7.0'
        FeatureExtractionv: '2.2.4'
        Cyclopsv: '2.0.2'
        EmpiricalCalibrationv: '2.0.0'
        OhdsiSharingv: '0.1.3'
        MethodEvaluationv: '1.0.2'
        Hydrav: '0.0.4'
        PredictionComparisonv: '1.0.0'
        CreateVpc: false
        VPCId: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-VPCID
        SubnetPublicA: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-AZAPublicId
        SubnetPublicB: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-AZBPublicId
        SubnetAppA: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-AZAPrivateId
        SubnetAppB: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-AZBPrivateId
        SubnetDataA: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-AZAPrivateId
        SubnetDataB: !ImportValue LZ-VPC-USE2-10-161-0-0-L-OHDSI-AZBPrivateId
        